# Default target
all: build

# Migrate local database
migrate-local:
	yarn dev-d1-migrate

# Migrate remote database
migrate-remote:
	yarn d1-migrate

# Deploy to Cloudflare Worker
deploy:
	yarn deploy
